### ISSUE TITLE
Epic user story 3: Checking out

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#4]
Kindly add at least 4 user stories for the "Checking out" epic user story.

**Comment by khalidsaadat** [comment]
Once done, open this file [Sprint 1] (https://docs.google.com/spreadsheets/d/1W-Vwu8acNQIfLbHaUwlDPs_vttswEiPfjp850s6jMhI/edit#gid=0) and change your task's status to 'DONE'.

**Comment by BrainOverfl0w** [comment]
I have 2 stories in mind : 
- As a normal user, I want to be able to view the subtotal of the current order, so that I can make changes to my cart if I want. 
- As a normal user, I want to be able to submit my billing and payment information, so that I can place my order.

**Comment by JIAYI615** [comment]
I have 3 stories in mind :
As a normal user, I want to be able to place an order, so that I can purchase the items I want.
As a normal user, I want to be able to view the current order, so that I can check the information of my order. 
As a normal user, I want to be able to cancel an order, so that I don’t have to pay for the items that are no longer needed.

**Comment by BrainOverfl0w** [comment]
I put some modifications and added another story :

-As a normal user, I want to be able to view the subtotal of the current order, so that I can make changes to my cart if I want.
-As a normal user, I want to be able to submit/edit my billing and payment information, so that I can place my order.
-As a normal user, I want to be able to put a gift or promo code, so that I can decrease the price of my purchase.
